
trigger:
- main

pool:
  vmImage: 'macos-latest'
  
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
    
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
    