
trigger:
- main

pool:
  vmImage: 'macos-latest'
  
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:

- script: ls -la
  displayName: 'Testing ls command'

- script: pwd
  displayName: 'Testing Pwd command'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'ol_distrib.p12'
    certPwd: Openlane2020

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'Openlane_Test1_Inhouse.mobileprovision'

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
    projectDirectory: '$(system.defaultWorkingDirectory)'
  displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'
    

- script: sh release_build.sh export_options_enterprise.plist iOSHelloWorld.xcworkspace Release 'iOSHelloWorld' 'iPhone Distribution`:` OPENLANE, Inc' 2.2 1
  displayName: 'Run Enterprise Buld via Script'

# - task: Xcode@5
#   inputs:
#     sdk: '$(sdk)'
#     scheme: '$(scheme)'
#     configuration: '$(configuration)'
#     actions: 'build'
#     xcWorkspacePath: '**/*.xcworkspace'
#     xcodeVersion: '11'
#     packageApp: true

# - task: AppCenterDistribute@3
#   inputs:
#     appFile: 
#     releaseNotesOption: 'input'
#     destinationType: 'groups'
#     appSlug: ''
#     serverEndpoint: ''
