
trigger:
- main

pool:
  vmImage: 'macos-latest'
  
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:

- script: ls -la
  displayName: 'Testing ls command'

- script: pwd
  displayName: 'Testing Pwd command'

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
    projectDirectory: '$(system.defaultWorkingDirectory)'
  displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'
    
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    actions: 'build'
    xcWorkspacePath: '**/*.xcworkspace'
    xcodeVersion: '11'
    packageApp: true

# - task: AppCenterDistribute@3
#   inputs:
#     appFile: 
#     releaseNotesOption: 'input'
#     destinationType: 'groups'
#     appSlug: ''
#     serverEndpoint: ''
