# Xcode

# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:

- task: Shell++@0
  inputs:
    type: 'InlineScript'
    script: |
      export ACR_REG="Hello world.$(Build.BuildNumber)"

      a=($(echo "$(Build.BuildNumber)" | tr '.' '\n'))
      echo "Hello Build Number = ${a[1]}"

      version="2.0.2"
      splitVersion=($(echo "$(version)" | tr '.' '\n'))

      for i in "${!splitVersion[@]}"
      do
          echo "$i=>${splitVersion[i]}"
      done

      echo "==============="
      echo "ACR_REG"
      echo "$ACR_REG"
      echo "==============="
            
      echo "##vso[task.setvariable variable=ACR_REGISTRY_LOGIN]$ACR_REG"

      echo "==============="
      echo "ACR reg login"
      echo $ACR_REGISTRY_LOGIN
      echo "==============="

- task: Shell++@0
  inputs:
    type: 'InlineScript'
    script: |
      echo "==============="
      echo "ACR reg login"
      echo $ACR_REGISTRY_LOGIN
      echo "$ACR_REGISTRY_LOGIN"
      echo "==============="
- task: Shell++@0
  inputs:
    type: 'InlineScript'
    script: 'echo Hey ''$(buildNumber)'''
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, default, specifyPath
